# Generated by Django 3.0.1 on 2020-02-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20191223_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='well',
            old_name='altitude',
            new_name='alt',
        ),
        migrations.RemoveField(
            model_name='oilfield',
            name='obzor_img',
        ),
        migrations.AddField(
            model_name='oilfield',
            name='map',
            field=models.ImageField(blank=True, upload_to='maps', verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Oil field'),
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='owner',
            field=models.CharField(blank=True, max_length=100, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='well',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=100),
            preserve_default=False,
        ),
    ]
