# Generated by Django 3.0.2 on 2020-02-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20200218_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilfield',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Oil field'),
        ),
    ]
