# Generated by Django 3.0.2 on 2020-02-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20200219_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilfield',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='maps', verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type'),
        ),
    ]
