# Generated by Django 3.0.3 on 2020-03-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20200229_1418'),
        ('db', '0006_auto_20200228_1114'),
    ]

    operations = [
    ]
