# Generated by Django 3.0.1 on 2019-12-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_photos', verbose_name='Profile photo'),
        ),
    ]
