# Generated by Django 3.0.3 on 2020-02-29 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 29, 9, 53, 47, 514402, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
